name: Optimize Images
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compress Images
        uses: im-open/image-compression@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
